Repository lanl/singularity-eos, pull requests merged in 2021-12, with the labels that each got.

#53 implement workaround for table edge issue
  sesame2spiner/generate_files.cpp
Labels: bug

#49 Spack package
  spack-repo/packages/singularity-eos/package.py
Labels: enhancement

#60 add build doc
  doc/sphinx/src/building.rst
Labels: documentation

#63 Fix the issue in extrapolation
  example/CMakeLists.txt
  example/get_sesame_state.cpp
  sesame2spiner/generate_files.cpp
  sesame2spiner/io_eospac.hpp
  singularity-eos/eos/eos_spiner.cpp
  test/eos_unit_tests.cpp
Labels: bug
