Repository lanl/singularity-eos, pull requests merged in 2022-07, with the labels that each got.

#150 changelog and cleanup
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  doc/sphinx/index.rst
  doc/sphinx/src/contributing.rst
  sesame2spiner/README.md
Labels: documentation

#146 Update spackage to use spack dependencies instead of submodules
  .gitlab-ci.yml
  CMakeLists.txt
  spack-repo/packages/catch2/package.py
  spack-repo/packages/ports-of-call/package.py
  spack-repo/packages/singularity-eos/package.py
  spack-repo/packages/spiner/package.py
Labels: enhancement

#157 Replace secant method with regula_falsi
  CHANGELOG.md
  singularity-eos/eos/eos_davis.cpp
  singularity-eos/eos/eos_gruneisen.cpp
  singularity-eos/eos/eos_jwl.cpp
Labels: bug
