Repository lanl/singularity-eos, pull requests merged in 2023-03, with the labels that each got.

#233 Add general entropy functionality to EOS
  .gitignore
  CHANGELOG.md
  doc/sphinx/src/models.rst
  doc/sphinx/src/modifiers.rst
  doc/sphinx/src/sphinx-doc.rst
  singularity-eos/eos/eos_base.hpp
  singularity-eos/eos/eos_davis.hpp
  singularity-eos/eos/eos_eospac.hpp
  singularity-eos/eos/eos_gruneisen.hpp
  singularity-eos/eos/eos_ideal.hpp
  singularity-eos/eos/eos_jwl.hpp
  singularity-eos/eos/eos_spiner.hpp
  singularity-eos/eos/eos_stellar_collapse.hpp
  singularity-eos/eos/eos_variant.hpp
  singularity-eos/eos/modifiers/eos_unitsystem.hpp
  singularity-eos/eos/modifiers/ramps_eos.hpp
  singularity-eos/eos/modifiers/relativistic_eos.hpp
  singularity-eos/eos/modifiers/scaled_eos.hpp
  singularity-eos/eos/modifiers/shifted_eos.hpp
  spack-repo/packages/singularity-eos/package.py
  test/test_eos_gruneisen.cpp
  test/test_eos_unit.cpp
Labels: enhancement

#239 Add explicit dependency to sphinx-rtd-theme (and through it, jQuery)
  CHANGELOG.md
  doc/sphinx/conf.py
Labels: documentation

#243 Limit undefined behaviour and fix some wharnings too
  CHANGELOG.md
  singularity-eos/base/root-finding-1d/root_finding.hpp
  singularity-eos/eos/eos_base.hpp
  singularity-eos/eos/eos_davis.hpp
  singularity-eos/eos/eos_gruneisen.hpp
  singularity-eos/eos/eos_jwl.hpp
  singularity-eos/eos/eos_spiner.hpp
  singularity-eos/eos/eos_stellar_collapse.hpp
  singularity-eos/eos/eos_vinet.hpp
  singularity-eos/eos/modifiers/ramps_eos.hpp
  singularity-eos/eos/singularity_eos.cpp
  test/profile_eos.cpp
  test/test_eos_unit.cpp
  test/test_eos_vinet.cpp
Labels: bug, clean-up
