Repository lanl/singularity-eos, pull requests merged in 2025-03, with the labels that each got.

#473 memory error in eospac wrapper
  CHANGELOG.md
  eospac-wrapper/eospac_wrapper.cpp
  singularity-eos/eos/eos_davis.hpp
  singularity-eos/eos/eos_gruneisen.hpp
Labels: bug

#478 fix kpt test and add a more extensive clang github-ci test suite
  .github/workflows/tests_clang.yml
  CHANGELOG.md
  test/test_kpt_models.cpp
Labels: bug, Testing

#480 Removes extraneous makefiles
  sesame2spiner/Makefile
  test/Makefile
Labels: clean-up

#481 Remove mutable from spiner-eos and fillin docs a bit
  CHANGELOG.md
  doc/sphinx/src/models.rst
  doc/sphinx/src/modifiers.rst
  singularity-eos/base/indexable_types.hpp
  singularity-eos/eos/eos_spiner.hpp
Labels: bug, documentation, clean-up

#483 Added optional argument to fortran interface
  singularity-eos/eos/eos_helmholtz.hpp
  singularity-eos/eos/singularity_eos.cpp
  singularity-eos/eos/singularity_eos.f90
  singularity-eos/eos/singularity_eos.hpp
  test/test_pte.cpp
Labels: enhancement
