Repository lanl/singularity-eos, pull requests merged in 2025-05, with the labels that each got.

#505 rename LogType::TRUE to LogType::DOUBLE
  CHANGELOG.md
  singularity-eos/base/fast-math/logs.hpp
Labels: bug, Robustness, interface

#504 Add Basic Fortran Interface Documentation
  CHANGELOG.md
  doc/sphinx/index.rst
  doc/sphinx/src/fortran.rst
Labels: documentation

#509 switch to const ref for CRTP then allow lambda to copy capture
  CHANGELOG.md
  singularity-eos/eos/eos_base.hpp
Labels: Performance
