Repository lanl/singularity-eos, pull requests merged in 2025-04, with the labels that each got.

#486 Move scratch_size and max_scratch_size into base class
  CHANGELOG.md
  singularity-eos/eos/eos_base.hpp
  singularity-eos/eos/eos_carnahan_starling.hpp
  singularity-eos/eos/eos_davis.hpp
  singularity-eos/eos/eos_electrons.hpp
  singularity-eos/eos/eos_gruneisen.hpp
  singularity-eos/eos/eos_helmholtz.hpp
  singularity-eos/eos/eos_ideal.hpp
  singularity-eos/eos/eos_jwl.hpp
  singularity-eos/eos/eos_mgusup.hpp
  singularity-eos/eos/eos_noble_abel.hpp
  singularity-eos/eos/eos_powermg.hpp
  singularity-eos/eos/eos_sap_polynomial.hpp
  singularity-eos/eos/eos_spiner.hpp
  singularity-eos/eos/eos_stellar_collapse.hpp
  singularity-eos/eos/eos_stiff.hpp
  singularity-eos/eos/eos_variant.hpp
  singularity-eos/eos/eos_vinet.hpp
Labels: clean-up

#494 [trivial] update spackage for release 1.9.2
  spack-repo/packages/singularity-eos/package.py
Labels: build

#496 [trivial] fix stellarcollapse2spiner in cmake
  CHANGELOG.md
  CMakeLists.txt
  doc/sphinx/src/building.rst
Labels: bug, build
